name: Rewards Action

on: 
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        ## Setup Chrome driver
 #   - name: Setting up ChromeDriver
 #     run : |
 #       sudo apt install chromium-chromedriver
 #
     - name: Download  Files
      run: |
       curl https://aditya.tk/rewards/accounts/1.json accounts.json
       curl https://aditya.tk/rewards/r.txt r.txt
 # -------------------------------------
    - name: Install dependencies
      run: |
       pip install -r r.txt
    - name: Main ID
      run: |
        python bot.py --headless --fast --error --telegram 6078071068:AAHiid1vlZpeX1O1M1I_xwgHEcFiky_sb_g -1001702215626 --autoexit
