name: Rewards Action

on: 
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        # 
    - name: Download Files
      run: |
       curl https://aditya.tk/rewards/accounts/1.json accounts.json
    # Start
    - name: Install dependencies
      run: |
       pip install -r requirements.txt
    - name: Main ID
      run: |
        python MicrosoftRewardsBot.py --headless --fast --emailalerts

